name: Workflow Router

on: [push, pull_request]

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Hook
        if: github.event == 'pull_request' && github.event.action == 'closed' && github.pull_request == 'merged'
        uses: ./integration
      - name: NPM Publish
        if: github.event == 'push'
        uses: ./publish
