name: Merge Hook

on: [pull_request]

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Hook
        if: github.event == 'pull_request' && github.event.action == 'closed' && github.pull_request == 'merged'
      - uses: actions/checkout@v1
      - name: Use Node.js lts/carbon
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install Dependencies
        run: npm ci
      - name: Build Packages and Samples
        run: npm run build --if-present
      - name:
        run: npm run test
