name: Merge Hook

on:
  push:
    branches:
      - master

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 8
      - name: Check if PR is merging and `npm ci`, build, and test
        if: github.event == 'pull_request' && github.event.action == 'closed' && github.pull_request == 'merged'
        run: |
          npm ci
          npm run build --if-present
          npm run test
